spring:
  application:
    name: ecommerce
  datasource:
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 10
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
        default_schema: ecommerce
        jdbc_batch_size: 100
        order_inserts: true
        order_updates: true
    hibernate:
      ddl-auto: none
    show-sql: ${SHOW_SQL:false}
    open-in-view: false
  flyway:
    enabled: true
    schemas: ecommerce
    baselineOnMigrate: true
  rabbitmq:
    password: password
    username: rabbitmq
jwt:
  public:
    key: classpath:app_public.key
  private:
    key: classpath:app.key
  issuer: br.com.ecommerce
ecommerce:
  storage:
    provider: fake
  payment:
    pagseguro:
      redirect-uri: ${PAG_SEGURO_REDIRECT_URL}?returnId=#orderId&redirectUrl=#redirectURL
    paypal:
      redirect-uri: ${PAYPAL_REDIRECT_URL}/#orderId?redirectUrl=#redirectURL
